project_name: image-formula-find
before:
  hooks:
    - go install golang.org/x/tools/cmd/goyacc@latest
    - goyacc -o calc.go -v calc.output calc.y
builds:
  -
    id: "draw1"
    binary: "draw1"
    dir: cmd/draw1
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  -
    id: "draw2"
    binary: "draw2"
    dir: cmd/draw2
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  -
    id: "fromRndStr"
    binary: "fromRndStr"
    dir: cmd/fromRndStr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  -
    id: "greensquare"
    binary: "greensquare"
    dir: cmd/greensquare
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  -
    id: "mutateAndSelect"
    binary: "mutateAndSelect"
    dir: cmd/mutateAndSelect
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  -
    id: "mutateFromRndStr"
    binary: "mutateFromRndStr"
    dir: cmd/mutateFromRndStr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  -
    id: "watchMutateAndSelect"
    binary: "watchMutateAndSelect"
    dir: cmd/watchMutateAndSelect
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - format: tar.gz
    on:
      goos:
        - linux
        - darwin
  - format: zip
    on:
      goos:
        - windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: Ubels Software Development
    homepage: https://github.com/arran4/
    maintainer: Arran Ubels <arran@ubels.com.au>
    description: NA
    license: Private
    formats:
      - apk
      - deb
      - rpm
    release: 1
    section: default
    priority: extra
